blueprint:
  name: Arrive Zone Notifications
  description: |
    # Zone Arriving Notifications
  domain: automation
alias: "Notification: Adam Arrived Home"
description: ""
trigger:
  - platform: zone
    entity_id: person.adam
    zone: zone.home
    event: enter
condition: []
action:
  - service: notify.mobile_app_fayes_iphone
    data:
      title: Adam Arrived Home
      message: Adam Has Arrived at Home
mode: single
