# Blueprint metadata
blueprint:
  name: HUE Smart Button (Multi-press)
  description: |
    # Philips HUE Smart Button - Multi-press Controller v0.2

alias: "Notification: Adam Arrived Home"
description: ""
trigger:
  - platform: zone
    entity_id: person.adam
    zone: zone.home
    event: enter
condition: []
action:
  - service: notify.mobile_app_fayes_iphone
    data:
      title: Adam Arrived Home
      message: Adam Has Arrived at 3 Heathfield Gate
mode: single
