blueprint:
  name: ZHA - Ecodim, 4 Channel remote
  description: 'Control any light using the Ecodim remote on ZHA'
  domain: automation
  input:
alias: "Notification: Adam Arrived Home"
description: ""
trigger:
  - platform: zone
    entity_id: person.adam
    zone: zone.home
    event: enter
condition: []
action:
  - service: notify.mobile_app_fayes_iphone
    data:
      title: Adam Arrived Home
      message: Adam Has Arrived at 3 Heathfield Gate
mode: single
