blueprint:
  name: Zone Leave Notifications
  description: |
    #  Zone Leaving Notifications V1.2
  domain: automation
alias: "Notification: Adam Left Home"
description: ""
trigger:
  - platform: zone
    entity_id: person.adam
    zone: zone.home
    event: leave
condition: []
action:
  - service: notify.mobile_app_fayes_iphone
    metadata: {}
    data:
      title: Adam Left Home
      message: Adam Left Home
mode: single
