<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'instanceid' => 'ocnefzzdmr0z',
  'passwordsalt' => 'FIfExFqJBCrtNvce4w256xhjV4LEaq',
  'secret' => 'MUTPat3M8oNSxnSnJeGUrajXCjwFy1/unlJ6QumCBhfEFNhm',
  'trusted_domains' => 
  array (
    0 => '[IP ADDRESS HERE]',
    1 => '[PUBLIC URL HERE]',
  ),
  'dbtype' => 'sqlite3',
  'version' => '28.0.2.5',
  'overwrite.cli.url' => '[IP ADDRESS HERE]',
  'dbname' => 'db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\APCu',
  'upgrade.disable-web' => true,
  'mail_from_address' => 'adam',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '[DOMAIN]',
  'mail_smtphost' => 'smtp.[DOMAIN]',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'adam@[DOMAIN]',
  'mail_smtppassword' => '',
  'app_install_overwrite' => 
  array (
    0 => 'files_markdown',
  ),
  'maintenance' => false,
);
